#include "http.h"
#include "config.h"
#include "system.h"
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <time.h>
#include <unistd.h>

static char session_token[65];
static int session_ready;

static void init_session(void){
    if(session_ready)return;
    FILE *f=fopen("/dev/urandom","rb");unsigned char b[32];size_t n=f?fread(b,1,sizeof(b),f):0;if(f)fclose(f);
    if(n!=sizeof(b)){srand((unsigned)(time(NULL)^(unsigned)getpid()));for(size_t i=0;i<sizeof(b);i++)b[i]=(unsigned char)(rand()&255);}
    static const char h[]="0123456789abcdef";for(size_t i=0;i<sizeof(b);i++){session_token[i*2]=h[b[i]>>4];session_token[i*2+1]=h[b[i]&15];}session_token[64]=0;session_ready=1;
}
static void response(int fd,const char *status,const char *type,const char *body,const char *extra){char h[1024];int n=snprintf(h,sizeof(h),"HTTP/1.1 %s\r\nContent-Type: %s\r\nContent-Length: %zu\r\nCache-Control: no-store, no-cache, must-revalidate\r\nPragma: no-cache\r\nConnection: close\r\n%s\r\n",status,type,strlen(body),extra?extra:"");send(fd,h,n,0);send(fd,body,strlen(body),0);}
static int hex(char c){if(c>='0'&&c<='9')return c-'0';if(c>='a'&&c<='f')return c-'a'+10;if(c>='A'&&c<='F')return c-'A'+10;return -1;}
static void url_decode(const char *src,char *dst,size_t size){size_t j=0;for(size_t i=0;src[i]&&j+1<size;i++){if(src[i]=='%'&&src[i+1]&&src[i+2]){int a=hex(src[i+1]),b=hex(src[i+2]);if(a>=0&&b>=0){dst[j++]=(char)((a<<4)|b);i+=2;continue;}}dst[j++]=src[i]=='+'?' ':src[i];}dst[j]=0;}
static int read_request(int fd,char *buf,size_t cap){size_t used=0;ssize_t n;size_t need=0;int header=0;while(used+1<cap){n=recv(fd,buf+used,cap-used-1,0);if(n<=0)break;used+=(size_t)n;buf[used]=0;if(!header){char *end=strstr(buf,"\r\n\r\n");if(end){header=1;char *cl=strcasestr(buf,"Content-Length:");if(cl)need=(size_t)strtoul(cl+15,NULL,10);size_t have=used-(size_t)((end+4)-buf);if(have>=need)break;} }else{char *end=strstr(buf,"\r\n\r\n");size_t have=end?used-(size_t)((end+4)-buf):0;if(have>=need)break;}}return (int)used;}
static int logged_in(const char *req){init_session();const char *p=req;while((p=strcasestr(p,"Cookie:"))){p+=7;const char *end=strstr(p,"\r\n");size_t len=end?(size_t)(end-p):strlen(p);char c[512];if(len>=sizeof(c))len=sizeof(c)-1;memcpy(c,p,len);c[len]=0;char expected[96];snprintf(expected,sizeof(expected),"PISESSION=%s",session_token);char *v=strstr(c,expected);if(v&&(v==c||v[-1]==';'||v[-1]==' '||v[-1]=='\t'))return 1;p=end?end:p+len;}return 0;}
static void file_response(int fd,const char *path,const char *type){FILE *f=fopen(path,"rb");if(!f){response(fd,"404 Not Found","text/plain","Not found",NULL);return;}fseek(f,0,SEEK_END);long len=ftell(f);rewind(f);if(len<0||len>1024*1024){fclose(f);response(fd,"500 Internal Server Error","text/plain","File error",NULL);return;}char *data=malloc((size_t)len+1);if(!data){fclose(f);response(fd,"500 Internal Server Error","text/plain","Memory error",NULL);return;}size_t got=fread(data,1,(size_t)len,f);data[got]=0;fclose(f);response(fd,"200 OK",type,data,NULL);free(data);}
static void login_api(int fd,const char *req){const char *body=strstr(req,"\r\n\r\n");if(!body){response(fd,"400 Bad Request","application/json","{\"ok\":false,\"error\":\"request body required\"}",NULL);return;}body+=4;char ru[128]={0},rp[256]={0},u[128],p[256];const char *a=strstr(body,"username="),*b=strstr(body,"password=");if(a)sscanf(a+9,"%127[^&]",ru);if(b)sscanf(b+9,"%255[^&]",rp);url_decode(ru,u,sizeof(u));url_decode(rp,p,sizeof(p));if(!strcmp(u,PI_MONITOR_USER)&&!strcmp(p,PI_MONITOR_PASSWORD)){init_session();char cookie[256];snprintf(cookie,sizeof(cookie),"Set-Cookie: PISESSION=%s; Path=/; HttpOnly; SameSite=Strict; Max-Age=28800\r\n",session_token);response(fd,"200 OK","application/json","{\"ok\":true}",cookie);}else response(fd,"401 Unauthorized","application/json","{\"ok\":false,\"error\":\"Invalid username or password\"}",NULL);}
static void terminal_api(int fd,const char *req){const char *body=strstr(req,"\r\n\r\n");char raw[256]={0},cmd[256]={0};if(body){body+=4;const char *c=strstr(body,"command=");if(c)sscanf(c+8,"%255[^&]",raw);}url_decode(raw,cmd,sizeof(cmd));const char *shell=NULL;if(!strcmp(cmd,"uptime"))shell="uptime";else if(!strcmp(cmd,"free -h"))shell="free -h";else if(!strcmp(cmd,"df -h"))shell="df -h /";else if(!strcmp(cmd,"uname -a"))shell="uname -a";else if(!strcmp(cmd,"ip addr"))shell="ip addr";else if(!strcmp(cmd,"systemctl status"))shell="systemctl status pi-monitor --no-pager";else {response(fd,"400 Bad Request","application/json","{\"error\":\"command not allowed\"}",NULL);return;}char out[8192]={0};FILE *q=popen(shell,"r");if(q){fread(out,1,sizeof(out)-1,q);pclose(q);}char esc[8192]={0};size_t j=0;for(size_t i=0;out[i]&&j+2<sizeof(esc);i++){if(out[i]=='\\'||out[i]=='\"')esc[j++]='\\';if(out[i]=='\n'){esc[j++]='\\';esc[j++]='n';}else if(out[i]!='\r')esc[j++]=out[i];}esc[j]=0;char json[8300];snprintf(json,sizeof(json),"{\"output\":\"%s\"}",esc);response(fd,"200 OK","application/json",json,NULL);}
static void api(int fd,const char *req,const char *path){char json[65536];if(!logged_in(req)){response(fd,"401 Unauthorized","application/json","{\"error\":\"login required\"}",NULL);return;}if(!strcmp(path,"/api/status")){system_status_json(json,sizeof(json));response(fd,"200 OK","application/json",json,NULL);return;}if(!strcmp(path,"/api/processes")){processes_json(json,sizeof(json));response(fd,"200 OK","application/json",json,NULL);return;}if(!strcmp(path,"/api/ports")){ports_json(json,sizeof(json));response(fd,"200 OK","application/json",json,NULL);return;}if(!strcmp(path,"/api/logs")){logs_json(json,sizeof(json));response(fd,"200 OK","application/json",json,NULL);return;}if(!strncmp(path,"/api/signal?",12)){int pid=0,sig=0;sscanf(path,"/api/signal?pid=%d&sig=%d",&pid,&sig);int ok=process_signal(pid,sig)==0;response(fd,ok?"200 OK":"400 Bad Request","application/json",ok?"{\"ok\":true}":"{\"ok\":false}",NULL);return;}if(!strcmp(path,"/api/terminal")){terminal_api(fd,req);return;}if(!strcmp(path,"/api/shutdown")){response(fd,"200 OK","application/json","{\"ok\":true}",NULL);sync();system("/sbin/shutdown -h now");return;}if(!strcmp(path,"/api/reboot")){response(fd,"200 OK","application/json","{\"ok\":true}",NULL);sync();system("/sbin/reboot");return;}if(!strcmp(path,"/api/logout")){response(fd,"200 OK","application/json","{\"ok\":true}","Set-Cookie: PISESSION=; Max-Age=0; Path=/; HttpOnly; SameSite=Strict\r\n");return;}response(fd,"404 Not Found","application/json","{\"error\":\"not found\"}",NULL);}
void handle_connection(int fd){char req[32768]={0},method[16]={0},path[512]={0};if(read_request(fd,req,sizeof(req))<=0){close(fd);return;}sscanf(req,"%15s %511s",method,path);char *query=strchr(path,'?');if(query&&strncmp(path,"/api/signal?",12)!=0)*query=0;if(!strcmp(method,"POST")&&!strcmp(path,"/api/login"))login_api(fd,req);else if(!strcmp(path,"/")||!strcmp(path,"/login"))file_response(fd,PI_MONITOR_WEB_ROOT "/login.html","text/html; charset=utf-8");else if(!strcmp(path,"/app.css"))file_response(fd,PI_MONITOR_WEB_ROOT "/app.css","text/css; charset=utf-8");else if(!strcmp(path,"/app.js"))file_response(fd,PI_MONITOR_WEB_ROOT "/app.js","application/javascript; charset=utf-8");else if(!strcmp(path,"/dashboard")){if(logged_in(req))file_response(fd,PI_MONITOR_WEB_ROOT "/dashboard.html","text/html; charset=utf-8");else response(fd,"302 Found","text/plain","Redirecting","Location: /login\r\n");}else if(!strncmp(path,"/api/",5))api(fd,req,path);else response(fd,"404 Not Found","text/plain","Not found",NULL);close(fd);}
