#include "system.h"
#include <dirent.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/statvfs.h>
#include <unistd.h>
#include <limits.h>

static unsigned long long mem_value(const char *wanted) { FILE *f=fopen("/proc/meminfo","r"); char line[160],name[64]; unsigned long long value; if(!f)return 0; while(fgets(line,sizeof(line),f)) if(sscanf(line,"%63[^:]: %llu",name,&value)==2&&!strcmp(name,wanted)){fclose(f);return value*1024ULL;} fclose(f);return 0; }
static double cpu_percent(void){FILE*f=fopen("/proc/stat","r");unsigned long long u,n,s,i,w,x,y,z;static unsigned long long ot,oi;double r=0;if(!f)return 0;if(fscanf(f,"cpu %llu %llu %llu %llu %llu %llu %llu %llu",&u,&n,&s,&i,&w,&x,&y,&z)==8){unsigned long long t=u+n+s+i+w+x+y+z,id=i+w,dt=t-ot,di=id-oi;if(ot&&dt)r=100.0*(double)(dt-di)/(double)dt;ot=t;oi=id;}fclose(f);return r;}
static unsigned long long uptime_seconds(void){FILE*f=fopen("/proc/uptime","r");double u=0;if(!f)return 0;fscanf(f,"%lf",&u);fclose(f);return(unsigned long long)u;}
static double load1(void){FILE*f=fopen("/proc/loadavg","r");double v=0;if(!f)return 0;fscanf(f,"%lf",&v);fclose(f);return v;}
static double temperature(void){const char*p[]={"/sys/class/thermal/thermal_zone0/temp","/sys/devices/virtual/thermal/thermal_zone0/temp",NULL};char b[64];for(int i=0;p[i];i++){FILE*f=fopen(p[i],"r");if(!f)continue;if(fgets(b,sizeof(b),f)){fclose(f);double v=strtod(b,NULL);return v>1000?v/1000.0:v;}fclose(f);}return -1;}
static unsigned long cpu_mhz(void){FILE*f=fopen("/sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq","r");unsigned long k=0;if(f){fscanf(f,"%lu",&k);fclose(f);if(k)return k/1000;}return 0;}
static unsigned long cpu_max_mhz(void){const char*p[]={"/sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq","/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq",NULL};for(int i=0;p[i];i++){FILE*f=fopen(p[i],"r");unsigned long k=0;if(f){fscanf(f,"%lu",&k);fclose(f);if(k)return k/1000;}}return 900;}
static void network_bytes(unsigned long long*rx,unsigned long long*tx){FILE*f=fopen("/proc/net/dev","r");char line[512],iface[64];unsigned long long a[16];*rx=*tx=0;if(!f)return;while(fgets(line,sizeof(line),f))if(sscanf(line," %63[^:]: %llu %llu %llu %llu %llu %llu %llu %llu %llu %llu %llu %llu %llu %llu %llu %llu",iface,&a[0],&a[1],&a[2],&a[3],&a[4],&a[5],&a[6],&a[7],&a[8],&a[9],&a[10],&a[11],&a[12],&a[13],&a[14],&a[15])==17&&strcmp(iface,"lo")){*rx+=a[0];*tx+=a[8];}fclose(f);}
static void hostname_value(char*o,size_t n){if(gethostname(o,n-1)<0)snprintf(o,n,"unknown");o[n-1]=0;}
void system_status_json(char*out,size_t size){struct statvfs fs;unsigned long long total=0,free_space=0,rt=mem_value("MemTotal"),ra=mem_value("MemAvailable"),rx,tx;char host[128];hostname_value(host,sizeof(host));if(!statvfs("/",&fs)){total=(unsigned long long)fs.f_blocks*fs.f_frsize;free_space=(unsigned long long)fs.f_bavail*fs.f_frsize;}network_bytes(&rx,&tx);unsigned long long used=rt>ra?rt-ra:0;double disk=total?100.0*(double)(total-free_space)/(double)total:0,temp=temperature();unsigned long cur=cpu_mhz(),max=cpu_max_mhz();if(!cur)cur=0;snprintf(out,size,"{\"cpu\":%.1f,\"ram_total\":%llu,\"ram_used\":%llu,\"ram_percent\":%.1f,\"disk_percent\":%.1f,\"disk_total\":%llu,\"disk_free\":%llu,\"uptime\":%llu,\"rx\":%llu,\"tx\":%llu,\"load1\":%.2f,\"temperature\":%.1f,\"cpu_mhz\":%lu,\"cpu_max_mhz\":%lu,\"hostname\":\"%s\"}",cpu_percent(),rt,used,rt?100.0*used/rt:0,disk,total,free_space,uptime_seconds(),rx,tx,load1(),temp,cur,max,host);}
void processes_json(char*out,size_t size){DIR*d=opendir("/proc");struct dirent*e;size_t used=0;int first=1;used+=snprintf(out+used,size-used,"[");if(!d){snprintf(out+used,size-used,"]");return;}while((e=readdir(d))&&used+256<size){if(e->d_type!=DT_DIR)continue;char*end;long pid=strtol(e->d_name,&end,10);if(*end||pid<=0)continue;char path[64],name[128],state='?';snprintf(path,sizeof(path),"/proc/%ld/stat",pid);FILE*f=fopen(path,"r");if(!f)continue;if(fscanf(f,"%*d (%127[^)]) %c",name,&state)!=2){fclose(f);continue;}fclose(f);used+=snprintf(out+used,size-used,"%s{\"pid\":%ld,\"name\":\"%s\",\"state\":\"%c\"}",first?"":",",pid,name,state);first=0;}closedir(d);snprintf(out+used,size-used,"]");}
void ports_json(char*out,size_t size){FILE*f=fopen("/proc/net/tcp","r");char line[512];unsigned int local;size_t used=0;int first=1;used+=snprintf(out+used,size-used,"[");if(f){fgets(line,sizeof(line),f);while(fgets(line,sizeof(line),f)&&used+128<size)if(sscanf(line," %*d: %*8X:%X",&local)==1){used+=snprintf(out+used,size-used,"%s{\"proto\":\"tcp\",\"port\":%u}",first?"":",",local);first=0;}fclose(f);}snprintf(out+used,size-used,"]");}
void logs_json(char*out,size_t size){FILE*f=popen("journalctl -u pi-monitor -n 150 --no-pager -o short-iso 2>&1","r");size_t used=0;char line[512];int first=1;used+=snprintf(out+used,size-used,"[");if(f){while(fgets(line,sizeof(line),f)&&used+700<size){size_t n=strlen(line);while(n&&(line[n-1]=='\n'||line[n-1]=='\r'))line[--n]=0;char esc[640];size_t j=0;for(size_t i=0;line[i]&&j+2<sizeof(esc);i++){if(line[i]=='\\'||line[i]=='\"')esc[j++]='\\';esc[j++]=line[i];}esc[j]=0;used+=snprintf(out+used,size-used,"%s\"%s\"",first?"":",",esc);first=0;}pclose(f);}snprintf(out+used,size-used,"]");}
int process_signal(int pid,int sig){if(pid<=1||(sig!=SIGSTOP&&sig!=SIGCONT&&sig!=SIGTERM&&sig!=SIGKILL))return -1;return kill(pid,sig);}

static void jesc(const char*in,char*out,size_t n){size_t j=0;for(size_t i=0;in[i]&&j+2<n;i++){if(in[i]=='\\'||in[i]=='\"')out[j++]='\\';if(in[i]=='\n'||in[i]=='\r'){out[j++]=' ';}else out[j++]=in[i];}out[j]=0;}
void disks_json(char*out,size_t size){FILE*f=popen("lsblk -b -P -n -o NAME,SIZE,FSTYPE,LABEL,MOUNTPOINTS 2>/dev/null","r");char line[1200],name[128],fs[128],label[256],mount[512];unsigned long long bytes;size_t u=0;int first=1;u+=snprintf(out+u,size-u,"[");if(f){while(fgets(line,sizeof(line),f)&&u+900<size){name[0]=fs[0]=label[0]=mount[0]=0;bytes=0;sscanf(line,"NAME=\"%127[^\"]\" SIZE=\"%llu\" FSTYPE=\"%127[^\"]\" LABEL=\"%255[^\"]\" MOUNTPOINTS=\"%511[^\"]\"",name,&bytes,fs,label,mount);char a[128],b[128],c[256],d[512];jesc(name,a,sizeof(a));jesc(fs,b,sizeof(b));jesc(label,c,sizeof(c));jesc(mount,d,sizeof(d));u+=snprintf(out+u,size-u,"%s{\"name\":\"%s\",\"size\":%llu,\"fstype\":\"%s\",\"label\":\"%s\",\"mount\":\"%s\"}",first?"":",",a,bytes,b,c,d);first=0;}pclose(f);}snprintf(out+u,size-u,"]");}
void files_json(char*out,size_t size,const char*path){char dir[PATH_MAX];if(!path||!*path)path="/";if(realpath(path,dir)==NULL){snprintf(out,size,"[]");return;}struct stat st;if(stat(dir,&st)!=0||!S_ISDIR(st.st_mode)){snprintf(out,size,"[]");return;}DIR*d=opendir(dir);if(!d){snprintf(out,size,"[]");return;}size_t u=0;int first=1;u+=snprintf(out+u,size-u,"[");struct dirent*e;while((e=readdir(d))&&u+700<size){if(!strcmp(e->d_name,".")||!strcmp(e->d_name,".."))continue;char full[PATH_MAX],esc[NAME_MAX*2+8];snprintf(full,sizeof(full),"%s/%s",dir,e->d_name);struct stat x;if(lstat(full,&x)!=0)continue;jesc(e->d_name,esc,sizeof(esc));const char*type=S_ISDIR(x.st_mode)?"dir":S_ISREG(x.st_mode)?"file":S_ISLNK(x.st_mode)?"link":"other";u+=snprintf(out+u,size-u,"%s{\"name\":\"%s\",\"type\":\"%s\",\"size\":%llu}",first?"":",",esc,type,(unsigned long long)x.st_size);first=0;}closedir(d);snprintf(out+u,size-u,"]");}
