const $=id=>document.getElementById(id);
const history={cpu:[],ram:[],temp:[],rx:[],tx:[]};
let currentPath='/';
async function api(url,options={}){const r=await fetch(url,{credentials:'same-origin',cache:'no-store',...options});if(r.status===401){location='/login';throw new Error('Session expired');}if(!r.ok)throw new Error(await r.text());return r.json();}
function bytes(n){n=Number(n)||0;if(n<1024)return `${n.toFixed(0)} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;if(n<1073741824)return `${(n/1048576).toFixed(1)} MB`;return `${(n/1073741824).toFixed(2)} GB`;}
function duration(s){let d=Math.floor(s/86400);s%=86400;let h=Math.floor(s/3600);s%=3600;let m=Math.floor(s/60);return `${d}d ${h}h ${m}m`;}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function push(k,v){history[k].push(Number(v)||0);if(history[k].length>60)history[k].shift();}
function draw(id,sets,min,max,labels){const c=$(id);if(!c)return;const r=c.getBoundingClientRect(),d=window.devicePixelRatio||1,w=Math.max(300,r.width),h=c.height||240;c.width=Math.floor(w*d);c.height=Math.floor(h*d);const x=c.getContext('2d');x.setTransform(d,0,0,d,0,0);x.clearRect(0,0,w,h);const pad={l:42,r:12,t:18,b:28},cw=w-pad.l-pad.r,ch=h-pad.t-pad.b;x.font='11px system-ui';x.fillStyle='#7890a6';x.strokeStyle='#213449';x.lineWidth=1;for(let i=0;i<=4;i++){const y=pad.t+ch*i/4;const val=max-(max-min)*i/4;x.beginPath();x.moveTo(pad.l,y);x.lineTo(w-pad.r,y);x.stroke();x.fillText(`${val.toFixed(max-min>50?0:1)}`,4,y+4);}x.fillText('now',w-pad.r-24,h-8);if(sets.some(s=>s.length)){sets.forEach((s,si)=>{if(!s.length)return;x.strokeStyle=['#4da3dc','#71c98d','#e2ad5b','#c77dff'][si%4];x.lineWidth=2;x.beginPath();s.forEach((v,i)=>{const xx=pad.l+(s.length===1?0:i*cw/(Math.max(1,s.length-1)));const yy=pad.t+ch-(Math.max(min,Math.min(max,v))-min)/(max-min)*ch;i?x.lineTo(xx,yy):x.moveTo(xx,yy)});x.stroke();});}if(labels){x.fillStyle='#9bb0c4';labels.forEach((v,i)=>x.fillText(v,pad.l+i*90,h-8));}}
function drawAll(){draw('chart',[history.cpu,history.ram],0,100,['CPU','RAM']);draw('cpuChart',[history.cpu],0,100);draw('memChart',[history.ram],0,100);const temps=history.temp.filter(v=>v>=0);draw('tempChart',[history.temp],0,Math.max(100,Math.ceil((Math.max(...temps,50)+5)/10)*10));const rx=history.rx,tx=history.tx,rd=rx.map((v,i)=>i?Math.max(0,(v-rx[i-1])*2):0),td=tx.map((v,i)=>i?Math.max(0,(v-tx[i-1])*2):0),mx=Math.max(1,...rd,...td);draw('netChart',[rd,td],0,mx);}
function updateAlerts(x){const a=[];if(x.cpu>=90)a.push(['warn','CPU usage is above 90%']);if(x.ram_percent>=90)a.push(['warn','Memory usage is above 90%']);if(x.disk_percent>=90)a.push(['warn','Root filesystem is above 90%']);if(x.temperature>=80)a.push(['warn',`CPU temperature is ${x.temperature.toFixed(1)}°C`]);if(!a.length)a.push(['good','All monitored thresholds are healthy']);$('alerts').innerHTML=a.map(v=>`<div class="alert ${v[0]}">${esc(v[1])}</div>`).join('');}
async function refresh(){try{const x=await api('/api/status?_='+Date.now());$('cpu').textContent=`${x.cpu.toFixed(1)}%`;$('load').textContent=`Load ${x.load1.toFixed(2)}`;$('ram').textContent=`${bytes(x.ram_used)} / ${bytes(x.ram_total)}`;$('ramPct').textContent=`${x.ram_percent.toFixed(1)}% used`;$('temp').textContent=x.temperature<0?'N/A':`${x.temperature.toFixed(1)}°C`;$('tempState').textContent=x.temperature<0?'Sensor unavailable':x.temperature>=80?'High':'Normal`;$('disk').textContent=`${x.disk_percent.toFixed(1)}%`;$('diskFree').textContent=`${bytes(x.disk_free)} free`;$('mhz').textContent=x.cpu_mhz?`${x.cpu_mhz} MHz`:'N/A';$('mhzMax').textContent=`Maximum ${x.cpu_max_mhz||900} MHz`;$('uptime').textContent=duration(x.uptime);$('hostname').textContent=x.hostname;$('host').textContent=x.hostname;$('rx').textContent=bytes(x.rx);$('tx').textContent=bytes(x.tx);$('lastUpdate').textContent=`Updated ${new Date().toLocaleTimeString()}`;push('cpu',x.cpu);push('ram',x.ram_percent);push('temp',x.temperature);push('rx',x.rx);push('tx',x.tx);updateAlerts(x);drawAll();}catch(e){const h=document.querySelector('.health span');if(h)h.textContent='Telemetry unavailable';}}
async function loadProcesses(){try{const list=await api('/api/processes?_='+Date.now());$('processList').innerHTML='<table><tr><th>PID</th><th>Name</th><th>State</th><th>Actions</th></tr>'+list.map(p=>`<tr><td>${p.pid}</td><td>${esc(p.name)}</td><td>${esc(p.state)}</td><td><button onclick="signalProcess(${p.pid},19)">Stop</button> <button onclick="signalProcess(${p.pid},18)">Resume</button> <button onclick="signalProcess(${p.pid},15)">Terminate</button></td></tr>`).join('')+'</table>';}catch(e){}}
async function signalProcess(pid,sig){if(!confirm(`Send signal ${sig} to PID ${pid}?`))return;await api(`/api/signal?pid=${pid}&sig=${sig}`,{method:'POST'});loadProcesses();}
async function loadPorts(){try{const list=await api('/api/ports?_='+Date.now());$('portList').innerHTML='<table><tr><th>Protocol</th><th>Port</th></tr>'+list.map(p=>`<tr><td>${esc(p.proto)}</td><td>${p.port}</td></tr>`).join('')+'</table>';}catch(e){}}
async function loadLogs(){try{const list=await api('/api/logs?_='+Date.now());$('logList').innerHTML=list.length?list.map(v=>`<div class="logline">${esc(v)}</div>`).join(''):'<div class="logline">No journal entries available.</div>';}catch(e){}}
function diskSize(n){return n?bytes(n):'--';}
async function loadDisks(){try{const list=await api('/api/disks?_='+Date.now());$('diskList').innerHTML='<table><tr><th>Device</th><th>Size</th><th>Filesystem</th><th>Label</th><th>Mount</th></tr>'+list.map(d=>`<tr><td>${esc(d.name)}</td><td>${diskSize(d.size)}</td><td>${esc(d.fstype||'--')}</td><td>${esc(d.label||'--')}</td><td>${esc(d.mount||'--')}</td></tr>`).join('')+'</table>';loadFiles(currentPath);}catch(e){$('diskList').textContent='Unable to read block devices';}}
async function loadFiles(path='/'){currentPath=path;$('filePath').textContent=path;try{const list=await api('/api/files?path='+encodeURIComponent(path)+'&_='+Date.now());$('fileList').innerHTML=list.length?list.sort((a,b)=>a.type==='dir'?-1:b.type==='dir'?1:a.name.localeCompare(b.name)).map(f=>f.type==='dir'?`<button class="fileitem" onclick="loadFiles(${JSON.stringify((path==='/'?'':path)+'/'+f.name)})">📁 ${esc(f.name)}</button>`:`<div class="fileitem file">📄 ${esc(f.name)} <small>${bytes(f.size)}</small></div>`).join(''):'<div class="logline">Empty directory</div>';}catch(e){$('fileList').textContent='Unable to read directory';}}
function goParent(){if(currentPath==='/')return;const p=currentPath.split('/').filter(Boolean);p.pop();loadFiles('/'+p.join('/'));}
async function runCommand(){const command=$('command').value;const out=$('consoleOutput');out.textContent=`$ ${command}\n\nRunning...`;try{const r=await api('/api/terminal',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'command='+encodeURIComponent(command)});out.textContent=`$ ${command}\n\n${r.output||''}`;}catch(e){out.textContent=e.message;}}
async function shutdownPi(){if(!confirm('Shut down the Raspberry Pi?'))return;await api('/api/shutdown',{method:'POST'});}
async function rebootPi(){if(!confirm('Reboot the Raspberry Pi?'))return;await api('/api/reboot',{method:'POST'});}
async function logout(){try{await api('/api/logout',{method:'POST'});}catch(e){}location='/login';}
function selectTab(id){document.querySelectorAll('.tab').forEach(x=>x.classList.remove('show'));document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));$(id).classList.add('show');document.querySelector(`[data-tab="${id}"]`).classList.add('active');if(id==='disks')loadDisks();drawAll();}
async function refreshAll(){await refresh();const active=document.querySelector('nav button.active')?.dataset.tab;if(active==='processes')await loadProcesses();else if(active==='network')await loadPorts();else if(active==='logs')await loadLogs();else if(active==='disks')await loadDisks();}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>selectTab(b.dataset.tab));
const form=$('loginForm');if(form){form.onsubmit=async e=>{e.preventDefault();const button=$('loginButton'),error=$('error');button.disabled=true;button.textContent='Signing in...';error.textContent='';try{const r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},credentials:'same-origin',body:new URLSearchParams(new FormData(form))});const data=await r.json();if(!r.ok||!data.ok)throw new Error(data.error||'Login failed');location='/dashboard';}catch(err){error.textContent=err.message;}finally{button.disabled=false;button.textContent='Sign in';}};}
if($('cpu')){refreshAll();setInterval(refresh,500);setInterval(()=>{const active=document.querySelector('nav button.active')?.dataset.tab;if(active==='processes')loadProcesses();else if(active==='network')loadPorts();else if(active==='logs')loadLogs();else if(active==='disks')loadDisks();},500);window.addEventListener('resize',drawAll);}
