const $=id=>document.getElementById(id);const history={cpu:[],ram:[],temp:[],rx:[],tx:[],t:[]};
async function api(url,options={}){const r=await fetch(url,{credentials:'same-origin',cache:'no-store',...options});if(r.status===401){location='/login';throw new Error('Session expired');}if(!r.ok)throw new Error(await r.text());return r.json();}
function bytes(n){if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;if(n<1073741824)return `${(n/1048576).toFixed(1)} MB`;return `${(n/1073741824).toFixed(2)} GB`;}
function duration(s){let d=Math.floor(s/86400);s%=86400;let h=Math.floor(s/3600);s%=3600;let m=Math.floor(s/60);return `${d}d ${h}h ${m}m`;}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function push(k,v){history[k].push(v);if(history[k].length>60)history[k].shift();}
function draw(id,sets,min=0,max=100){const c=$(id);if(!c)return;const r=c.getBoundingClientRect(),d=window.devicePixelRatio||1,w=Math.max(300,r.width),h=c.height||220;c.width=w*d;c.height=h*d;const x=c.getContext('2d');x.scale(d,d);x.clearRect(0,0,w,h);x.strokeStyle='#1d3044';x.lineWidth=1;for(let i=1;i<5;i++){let y=i*h/5;x.beginPath();x.moveTo(0,y);x.lineTo(w,y);x.stroke();}sets.forEach((s,si)=>{if(!s.length)return;x.strokeStyle=['#4da3dc','#71c98d','#e2ad5b'][si%3];x.lineWidth=2;x.beginPath();s.forEach((v,i)=>{let xx=s.length===1?0:i*(w/(Math.max(1,s.length-1)));let yy=h-(Math.max(min,Math.min(max,v))-min)/(max-min)*h;i?x.lineTo(xx,yy):x.moveTo(xx,yy)});x.stroke()});}
function drawAll(){draw('chart',[history.cpu,history.ram,history.temp.map(v=>v<0?0:v)],0,100);draw('cpuChart',[history.cpu],0,100);draw('memChart',[history.ram,history.temp.map(v=>v<0?0:v)],0,100);let rx=history.rx,tx=history.tx;let rd=rx.map((v,i)=>i?Math.max(0,v-rx[i-1]):0),td=tx.map((v,i)=>i?Math.max(0,v-tx[i-1]):0);let mx=Math.max(1,...rd,...td);draw('netChart',[rd,td],0,mx);}
function updateAlerts(x){const a=[];if(x.cpu>=90)a.push(['warn','CPU sustained above 90%']);if(x.ram_percent>=90)a.push(['warn','Memory usage above 90%']);if(x.disk_percent>=90)a.push(['warn','Root filesystem above 90%']);if(x.temperature>=80)a.push(['warn',`CPU temperature ${x.temperature.toFixed(1)}°C`]);if(!a.length)a.push(['good','All monitored thresholds are healthy']);$('alerts').innerHTML=a.map(v=>`<div class="alert ${v[0]}">${esc(v[1])}</div>`).join('');}
async function refresh(){try{const x=await api('/api/status?_='+Date.now());$('cpu').textContent=`${x.cpu.toFixed(1)}%`;$('load').textContent=`Load ${x.load1.toFixed(2)}`;$('ram').textContent=`${bytes(x.ram_used)} / ${bytes(x.ram_total)}`;$('ramPct').textContent=`${x.ram_percent.toFixed(1)}% used`;$('temp').textContent=x.temperature<0?'N/A':`${x.temperature.toFixed(1)}°C`;$('tempState').textContent=x.temperature<0?'Sensor unavailable':x.temperature>=80?'High':'Normal';$('disk').textContent=`${x.disk_percent.toFixed(1)}%`;$('diskFree').textContent=`${bytes(x.disk_free)} free`;$('mhz').textContent=x.cpu_mhz?`${x.cpu_mhz} MHz`:'N/A';$('uptime').textContent=duration(x.uptime);$('hostname').textContent=x.hostname;$('host').textContent=x.hostname;$('rx').textContent=bytes(x.rx);$('tx').textContent=bytes(x.tx);$('lastUpdate').textContent=`Updated ${new Date().toLocaleTimeString()}`;push('cpu',x.cpu);push('ram',x.ram_percent);push('temp',x.temperature);push('rx',x.rx);push('tx',x.tx);updateAlerts(x);drawAll();}catch(e){const h=document.querySelector('.health span');if(h)h.textContent='Telemetry unavailable';}}
async function loadProcesses(){const list=await api('/api/processes?_='+Date.now());$('processList').innerHTML='<table><tr><th>PID</th><th>Name</th><th>State</th><th>Actions</th></tr>'+list.map(p=>`<tr><td>${p.pid}</td><td>${esc(p.name)}</td><td>${esc(p.state)}</td><td><button onclick="signalProcess(${p.pid},19)">Stop</button> <button onclick="signalProcess(${p.pid},18)">Resume</button> <button onclick="signalProcess(${p.pid},15)">Terminate</button></td></tr>`).join('')+'</table>';}
async function signalProcess(pid,sig){if(!confirm(`Send signal ${sig} to PID ${pid}?`))return;await api(`/api/signal?pid=${pid}&sig=${sig}`,{method:'POST'});loadProcesses();}
async function loadPorts(){const list=await api('/api/ports?_='+Date.now());$('portList').innerHTML='<table><tr><th>Protocol</th><th>Port</th></tr>'+list.map(p=>`<tr><td>${esc(p.proto)}</td><td>${p.port}</td></tr>`).join('')+'</table>';}
async function loadLogs(){const list=await api('/api/logs?_='+Date.now());$('logList').innerHTML=list.length?list.map(v=>`<div class="logline">${esc(v)}</div>`).join(''):'<div class="logline">No journal entries available.</div>';}
async function runCommand(){const command=$('command').value;const out=$('consoleOutput');out.textContent=`$ ${command}\n\nRunning...`;try{const r=await api('/api/terminal',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'command='+encodeURIComponent(command)});out.textContent=`$ ${command}\n\n${r.output||''}`;}catch(e){out.textContent=e.message;}}
async function shutdownPi(){if(!confirm('Shut down the Raspberry Pi?'))return;await api('/api/shutdown',{method:'POST'});}
async function rebootPi(){if(!confirm('Reboot the Raspberry Pi?'))return;await api('/api/reboot',{method:'POST'});}
async function logout(){try{await api('/api/logout',{method:'POST'});}catch(e){}location='/login';}
function selectTab(id){document.querySelectorAll('.tab').forEach(x=>x.classList.remove('show'));document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));$(id).classList.add('show');document.querySelector(`[data-tab="${id}"]`).classList.add('active');if(id==='processes')loadProcesses();if(id==='network')loadPorts();if(id==='logs')loadLogs();drawAll();}
function refreshAll(){refresh();const active=document.querySelector('nav button.active')?.dataset.tab;if(active==='processes')loadProcesses();if(active==='network')loadPorts();if(active==='logs')loadLogs();}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>selectTab(b.dataset.tab));
const form=$('loginForm');if(form){form.onsubmit=async e=>{e.preventDefault();const button=$('loginButton'),error=$('error');button.disabled=true;button.textContent='Signing in...';error.textContent='';try{const r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(new FormData(form))});const data=await r.json();if(!r.ok||!data.ok)throw new Error(data.error||'Login failed');location='/dashboard';}catch(err){error.textContent=err.message;}finally{button.disabled=false;button.textContent='Sign in';}};}
if($('cpu')){refresh();setInterval(refresh,2000);setInterval(()=>{const active=document.querySelector('nav button.active')?.dataset.tab;if(active==='logs')loadLogs();},15000);window.addEventListener('resize',drawAll);}
